package:
  name: cimcb_lite
  version: 0.0.6

requirements:
  build:
    - numpy
    - pandas
    - bokeh
    - scipy
    - scikit-learn
    - tqdm
    - xlrd

  run:
    - numpy
    - pandas
    - bokeh
    - scipy
    - scikit-learn
    - tqdm
    - xlrd

about:
  home: https://github.com/CIMCB
  license: "http://www.apache.org/licenses/LICENSE-2.0.html"
