package:
  name: cimcb_lite
  version: 0.0.2

source:
  fn: cimcb_lite-0.0.1.tar.gz
  url: https://github.com/KevinMMendez/cimcb_lite/cimcb_lite-0.0.1.tar.gz
  sha256: ceddf14e3a6ccf006cf048417fcedf80c5f533db9a3b531b402b38447aa3c45f 


requirements:
  build:
    - numpy
    - pandas
    - bokeh
    - scipy
    - scikit-learn
    - tqdm
    - xlrd

  run:
    - numpy
    - pandas
    - bokeh
    - scipy
    - scikit-learn
    - tqdm
    - xlrd

about:
  home: https://github.com/CIMCB
  license: "http://www.apache.org/licenses/LICENSE-2.0.html"
