package:
  name: cimcb_lite
  version: 0.0.15

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - numpy >=1.12.1
    - pandas >=0.24.1
    - bokeh >=0.13.0
    - scipy
    - scikit-learn
    - setuptools
    - statsmodels
    - python
    - tqdm
    - xlrd

  run:
    - numpy >=1.12.1
    - pandas >=0.24.1
    - bokeh >=0.13.0
    - scipy
    - scikit-learn
    - statsmodels
    - python
    - tqdm
    - xlrd

about:
  home: https://github.com/CIMCB
